"""
=====================================================================
 Full Dataset GFN2-xTB Pairwise Interaction Energy Pipeline
 Covers all unique pairs in index_with_anion.csv:
   - 125 Anion-Refrigerant pairs
   - 93 Cation-Refrigerant pairs
   Total: 218 unique pairs
 
 Features:
   1. Multi-orientation sampling (4 spatial orientations per pair)
   2. Lowest-energy converged configuration selection
   3. Checkpoint & Resume: automatically skips already computed pairs
   4. Exports Delta_E_int (kcal/mol) and d_min (Angstrom)
=====================================================================
"""

import os
import sys
import re
import math
import shutil
import subprocess
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

# --- KAGGLE / LOCAL XTB PATH RESOLUTION & AUTO-INSTALL ---
xtb_root = '/kaggle/working/xtb-dist'
if not os.path.exists(os.path.join(xtb_root, 'bin', 'xtb')) and os.path.exists('/kaggle/working'):
    print("📦 正在自动下载并解压 xTB Linux 二进制引擎 (GFN2-xTB)...")
    os.system("cd /kaggle/working && wget -q https://github.com/grimme-lab/xtb/releases/download/v6.6.1/xtb-6.6.1-linux-x86_64.tar.xz && tar -xf xtb-6.6.1-linux-x86_64.tar.xz && mv xtb-6.6.1 xtb-dist && rm -f xtb-6.6.1-linux-x86_64.tar.xz")

if os.path.exists(xtb_root):
    os.environ['PATH'] = f"{xtb_root}/bin:" + os.environ.get('PATH', '')
    os.environ['XTBPATH'] = f"{xtb_root}/share/xtb"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '..'))
INPUT_CSV = os.path.join(ROOT_DIR, 'index_with_anion.csv')
OUTPUT_CSV = os.path.join(SCRIPT_DIR, 'full_pair_interaction_results.csv')
WORK_DIR = os.path.join(SCRIPT_DIR, 'full_xtb_work')

FLOAT_RE = r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[EeDd][+-]?\d+)?"
HARTREE_TO_KCAL = 627.509474

def safe_name(name):
    return re.sub(r'[^\w\-.]', '_', str(name))

def parse_energy(text):
    matches = re.findall(r'TOTAL ENERGY\s+(' + FLOAT_RE + r')\s+Eh', text)
    if matches:
        val = matches[-1].replace("D", "E").replace("d", "e")
        return float(val)
    return None

def check_convergence(text):
    return bool(re.search(r'GEOMETRY OPTIMIZATION CONVERGED|normal termination of xtb', text, re.I))

def build_monomer_3d(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    res = AllChem.EmbedMolecule(mol, params)
    if res == -1:
        res = AllChem.EmbedMolecule(mol, useRandomCoords=True, randomSeed=42)
        if res == -1:
            return None
    try:
        AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
    except Exception:
        try:
            AllChem.UFFOptimizeMolecule(mol, maxIters=500)
        except Exception:
            pass
    return mol

def get_coords(mol):
    conf = mol.GetConformer()
    return conf.GetPositions()

def write_xyz(atom_symbols, coords, filepath):
    with open(filepath, 'w') as f:
        f.write(f"{len(atom_symbols)}\nGenerated by Full Interaction Pipeline\n")
        for sym, (x, y, z) in zip(atom_symbols, coords):
            f.write(f"{sym:<3} {x:12.6f} {y:12.6f} {z:12.6f}\n")

def run_xtb_opt(xyz_file, charge, work_dir, opt_level='tight'):
    os.makedirs(work_dir, exist_ok=True)
    xyz_name = os.path.basename(xyz_file)
    dst_xyz = os.path.join(work_dir, xyz_name)
    if os.path.abspath(xyz_file) != os.path.abspath(dst_xyz):
        shutil.copyfile(xyz_file, dst_xyz)

    # 统一采用 GFN2-xTB tight 收敛标准，保证单体与二聚体优化协议 100% 同源
    cmd = ['xtb', xyz_name, '--opt', opt_level, '--gfn', '2', '-c', str(charge)]
    try:
        res = subprocess.run(
            cmd,
            cwd=work_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=300
        )
        out = res.stdout + "\n" + res.stderr
        converged = check_convergence(out)
        energy = parse_energy(out)
        
        opt_xyz = os.path.join(work_dir, 'xtbopt.xyz')
        final_xyz = opt_xyz if os.path.exists(opt_xyz) else dst_xyz
        return energy, converged, final_xyz, out
    except Exception as e:
        return None, False, None, str(e)

def compute_min_distance(xyz_file, n_ion_atoms):
    if not os.path.exists(xyz_file):
        return None
    with open(xyz_file, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]
    if len(lines) < 3:
        return None
    
    coords = []
    for line in lines[2:]:
        parts = line.split()
        if len(parts) >= 4:
            coords.append([float(parts[1]), float(parts[2]), float(parts[3])])
    
    coords = np.array(coords)
    if len(coords) <= n_ion_atoms:
        return None
    
    ion_coords = coords[:n_ion_atoms]
    ref_coords = coords[n_ion_atoms:]
    
    diff = ion_coords[:, np.newaxis, :] - ref_coords[np.newaxis, :, :]
    dists = np.sqrt(np.sum(diff**2, axis=-1))
    return float(np.min(dists))

def adjust_min_distance(ion_xyz, ref_xyz, target_dist=3.2, tol=1e-3, max_iter=10):
    """
    精确调整两个分子片段之间的最近原子间距至 target_dist (默认 3.2 Å)。
    采用最近原子连线方向的多轮迭代微调算法，保证非对称异构体表面原子接触距离严格精确。
    """
    ref_xyz = ref_xyz.copy()

    for _ in range(max_iter):
        diff = ion_xyz[:, None, :] - ref_xyz[None, :, :]
        dists = np.linalg.norm(diff, axis=-1)

        i, j = np.unravel_index(np.argmin(dists), dists.shape)
        current_min_d = dists[i, j]

        if abs(current_min_d - target_dist) < tol:
            break

        direction = ref_xyz[j] - ion_xyz[i]
        norm = np.linalg.norm(direction)
        if norm < 1e-12:
            break

        direction /= norm
        # 将整个 ref fragment 沿当前最近原子连线方向平移
        ref_xyz += direction * (target_dist - current_min_d)

    final_dmin = np.min(np.linalg.norm(ion_xyz[:, None, :] - ref_xyz[None, :, :], axis=-1))
    assert abs(final_dmin - target_dist) < 1e-2, \
        f"🚨 初始几何间距调整失败！期望 {target_dist} Å，实际 {final_dmin:.4f} Å"

    return ref_xyz

def create_dimer_orientations(ion_mol, ref_mol, target_dist=3.2):
    """
    在 4 个正交与旋转方向进行多初始构象采样 (Initial Orientation Sampling)，
    并严格保证最近原子接触距离 d_min = 3.2 Å。
    """
    ion_syms = [a.GetSymbol() for a in ion_mol.GetAtoms()]
    ref_syms = [a.GetSymbol() for a in ref_mol.GetAtoms()]
    combined_syms = ion_syms + ref_syms
    
    ion_xyz = get_coords(ion_mol)
    ref_xyz = get_coords(ref_mol)
    
    ion_xyz = ion_xyz - np.mean(ion_xyz, axis=0)
    ref_xyz = ref_xyz - np.mean(ref_xyz, axis=0)
    
    orientations = []
    
    # Orient 1: +X direction
    c1_raw = ref_xyz + np.array([target_dist + np.max(ion_xyz[:,0]) - np.min(ref_xyz[:,0]), 0, 0])
    c1 = adjust_min_distance(ion_xyz, c1_raw, target_dist)
    orientations.append(np.vstack([ion_xyz, c1]))
    
    # Orient 2: -X direction
    c2_raw = ref_xyz + np.array([-target_dist + np.min(ion_xyz[:,0]) - np.max(ref_xyz[:,0]), 0, 0])
    c2 = adjust_min_distance(ion_xyz, c2_raw, target_dist)
    orientations.append(np.vstack([ion_xyz, c2]))
    
    # Orient 3: +Z direction
    c3_raw = ref_xyz + np.array([0, 0, target_dist + np.max(ion_xyz[:,2]) - np.min(ref_xyz[:,2])])
    c3 = adjust_min_distance(ion_xyz, c3_raw, target_dist)
    orientations.append(np.vstack([ion_xyz, c3]))
    
    # Orient 4: -Z direction with 90 deg Y-rotation
    R_y = np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]])
    ref_rot = np.dot(ref_xyz, R_y.T)
    c4_raw = ref_rot + np.array([0, 0, -target_dist + np.min(ion_xyz[:,2]) - np.max(ref_rot[:,2])])
    c4 = adjust_min_distance(ion_xyz, c4_raw, target_dist)
    orientations.append(np.vstack([ion_xyz, c4]))
    
    return combined_syms, orientations, len(ion_syms)

def main():
    print("="*70)
    print("  Full Dataset GFN2-xTB Pairwise Interaction Energy Pipeline")
    print("="*70)
    
    try:
        chk = subprocess.run(['xtb', '--version'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        print(f"✅ xTB 引擎就绪: {chk.stdout.splitlines()[0] if chk.stdout else 'Active'}")
    except Exception:
        print("❌ 未在 PATH 中找到 xtb 可执行文件！请确认已安装并在终端可用。")
        return

    os.makedirs(WORK_DIR, exist_ok=True)
    df_data = pd.read_csv(INPUT_CSV)
    
    # 1. 收集所有唯一的单体
    unique_refs = df_data[['refrigerant', 'refri_smiles']].drop_duplicates().set_index('refrigerant')['refri_smiles'].to_dict()
    unique_anions = df_data[['anion', 'anion_smiles']].drop_duplicates().set_index('anion')['anion_smiles'].to_dict()
    unique_cations = df_data[['cation', 'cation_smiles']].drop_duplicates().set_index('cation')['cation_smiles'].to_dict()
    
    print(f"📊 数据集规模: {len(unique_refs)} 种制冷剂, {len(unique_anions)} 种阴离子, {len(unique_cations)} 种阳离子")

    # 2. 单体能量计算与缓存
    print("\n[Step 1/2] 优化单体孤立能量 (Monomer Reference Energies)...")
    monomer_energies = {}
    
    all_monomers = []
    for r_name, r_smi in unique_refs.items():
        all_monomers.append(('Refrigerant', r_name, r_smi, 0))
    for a_name, a_smi in unique_anions.items():
        all_monomers.append(('Anion', a_name, a_smi, -1))
    for c_name, c_smi in unique_cations.items():
        all_monomers.append(('Cation', c_name, c_smi, 1))

    for cat, name, smi, charge in all_monomers:
        tag = safe_name(name)
        work = os.path.join(WORK_DIR, f"mono_{tag}")
        xyz_file = os.path.join(work, f"{tag}.xyz")
        os.makedirs(work, exist_ok=True)
        
        if not os.path.exists(xyz_file):
            mol = build_monomer_3d(smi)
            if mol is None:
                print(f"  ❌ RDKit 无法解析单体 3D: {name}")
                continue
            write_xyz([a.GetSymbol() for a in mol.GetAtoms()], get_coords(mol), xyz_file)
            
        e, conv, _, _ = run_xtb_opt(xyz_file, charge, work)
        monomer_energies[name] = e
        print(f"  - {cat:<11} {name:<12}: E = {e if e else 0.0:.6f} Eh (收敛: {conv})")

    # 3. 收集所有配对任务
    anion_pairs = df_data[['anion', 'refrigerant', 'anion_smiles', 'refri_smiles']].drop_duplicates()
    cation_pairs = df_data[['cation', 'refrigerant', 'cation_smiles', 'refri_smiles']].drop_duplicates()
    
    pair_tasks = []
    for _, row in anion_pairs.iterrows():
        pair_tasks.append(('Anion-Ref', row['anion'], row['anion_smiles'], -1, row['refrigerant'], row['refri_smiles'], 0, -1))
    for _, row in cation_pairs.iterrows():
        pair_tasks.append(('Cation-Ref', row['cation'], row['cation_smiles'], 1, row['refrigerant'], row['refri_smiles'], 0, 1))

    print(f"\n[Step 2/2] 全量多构型配对复合物优化 (共 {len(pair_tasks)} 个配对任务)...")

    # 读取已完成的结果（断点续算）
    completed_keys = set()
    if os.path.exists(OUTPUT_CSV):
        df_exist = pd.read_csv(OUTPUT_CSV)
        for _, r in df_exist.iterrows():
            completed_keys.add((r['Pair_Type'], str(r['Ion_Name']), str(r['Refrigerant'])))
        print(f"🔄 检测到已有进度，已完成 {len(completed_keys)} / {len(pair_tasks)} 个任务，自动跳过...")

    for idx, (pair_type, ion_name, ion_smi, ion_q, ref_name, ref_smi, ref_q, dimer_q) in enumerate(pair_tasks, 1):
        if (pair_type, str(ion_name), str(ref_name)) in completed_keys:
            continue

        pair_tag = f"{safe_name(ion_name)}__{safe_name(ref_name)}"
        print(f"\n▶ [{idx}/{len(pair_tasks)}] 正在优化: [{pair_type}] {ion_name} + {ref_name} (Charge = {dimer_q})...")
        
        ion_mol = build_monomer_3d(ion_smi)
        ref_mol = build_monomer_3d(ref_smi)
        if ion_mol is None or ref_mol is None:
            print(f"   ❌ 无法生成 3D 构象，跳过！")
            continue

        syms, orientations, n_ion_atoms = create_dimer_orientations(ion_mol, ref_mol)
        
        orient_results = []
        for o_idx, coords in enumerate(orientations, 1):
            sub_work = os.path.join(WORK_DIR, f"pair_{pair_tag}_ori{o_idx}")
            init_xyz = os.path.join(sub_work, "init.xyz")
            os.makedirs(sub_work, exist_ok=True)
            write_xyz(syms, coords, init_xyz)
            
            e_opt, conv, final_xyz, _ = run_xtb_opt(init_xyz, dimer_q, sub_work)
            d_min = compute_min_distance(final_xyz, n_ion_atoms) if final_xyz else None
            
            if e_opt is not None and conv:
                orient_results.append({
                    'orient_idx': o_idx,
                    'E_complex': e_opt,
                    'd_min': d_min
                })
        
        if orient_results:
            best = min(orient_results, key=lambda x: x['E_complex'])
            e_complex = best['E_complex']
            best_d_min = best['d_min']
            e_ion = monomer_energies.get(ion_name)
            e_ref = monomer_energies.get(ref_name)
            
            if e_ion is not None and e_ref is not None:
                delta_e_kcal = (e_complex - (e_ion + e_ref)) * HARTREE_TO_KCAL
            else:
                delta_e_kcal = None
                
            print(f"   🏆 最优构型 (Ori {best['orient_idx']}): ΔE_int = {delta_e_kcal if delta_e_kcal else 0.0:.2f} kcal/mol | d_min = {best_d_min:.2f} Å (收敛 {len(orient_results)}/4)")
            
            res_row = {
                'Pair_Type': pair_type,
                'Ion_Name': ion_name,
                'Refrigerant': ref_name,
                'E_complex_Eh': e_complex,
                'E_ion_Eh': e_ion,
                'E_ref_Eh': e_ref,
                'Delta_E_int_kcal_mol': delta_e_kcal,
                'd_min_Angstrom': best_d_min,
                'Best_Orientation': best['orient_idx'],
                'N_Converged_Orientations': len(orient_results),
                'Status': 'Success'
            }
        else:
            print(f"   🚨 该配对全部 4 种构型均优化失败！")
            res_row = {
                'Pair_Type': pair_type,
                'Ion_Name': ion_name,
                'Refrigerant': ref_name,
                'E_complex_Eh': None,
                'E_ion_Eh': monomer_energies.get(ion_name),
                'E_ref_Eh': monomer_energies.get(ref_name),
                'Delta_E_int_kcal_mol': None,
                'd_min_Angstrom': None,
                'Best_Orientation': None,
                'N_Converged_Orientations': 0,
                'Status': 'Failed'
            }

        # 实时追加保存，防止中断
        df_new = pd.DataFrame([res_row])
        if not os.path.exists(OUTPUT_CSV):
            df_new.to_csv(OUTPUT_CSV, index=False)
        else:
            df_new.to_csv(OUTPUT_CSV, mode='a', header=False, index=False)

    print("\n" + "="*70)
    print(f"🎉 全部 218 组配对相互作用能计算完成！结果保存在: {OUTPUT_CSV}")
    print("="*70)

if __name__ == '__main__':
    main()
