"""
=====================================================================
 Pilot GFN2-xTB Pairwise Interaction Energy Calculator
 Target: 21 Representative Pilot Pairs
   - 3 Refrigerants: R32 (success), R152a (boundary), R23 (failure)
   - 5 Anions: [Ac], [Tf2N], [BF4], [OTf], [PF6] (15 pairs)
   - 2 Cations: [BMIM], [EMIM] (6 pairs)
 
 Methodological Rigor:
   1. Multi-orientation initial sampling (4 spatial orientations per pair)
   2. Lowest-energy converged configuration selection
   3. Inter-fragment distance sanity checks (d_min)
   4. Explicit gas-phase pairwise interaction energy:
      Delta_E = (E_complex - E_ion - E_ref) * 627.5095 kcal/mol
=====================================================================
"""

import os
import sys
import re
import math
import shutil
import subprocess
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

# --- KAGGLE / LOCAL XTB PATH RESOLUTION ---
xtb_root = '/kaggle/working/xtb-dist'
if os.path.exists(xtb_root):
    os.environ['PATH'] = f"{xtb_root}/bin:" + os.environ.get('PATH', '')
    os.environ['XTBPATH'] = f"{xtb_root}/share/xtb"

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
OUTPUT_CSV = os.path.join(os.path.dirname(__file__), 'pilot_pair_interaction_results.csv')
WORK_DIR = os.path.join(os.path.dirname(__file__), 'pilot_xtb_work')

PILOT_REFRIGERANTS = {
    'R32':   'C(F)F',
    'R152a': 'CC(F)F',
    'R23':   'C(F)(F)F'
}

PILOT_ANIONS = {
    '[Ac]':   'CC(=O)[O-]',
    '[Tf2N]': 'FC(S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F)(F)F',
    '[BF4]':  'F[B-](F)(F)F',
    '[OTf]':  'FC(F)(F)S(=O)(=O)[O-]',
    '[PF6]':  'F[P-](F)(F)(F)(F)F'
}

PILOT_CATIONS = {
    '[BMIM]': 'CCCCn1cc[n+](C)c1',
    '[EMIM]': 'CCn1cc[n+](C)c1'
}

FLOAT_RE = r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[EeDd][+-]?\d+)?"
HARTREE_TO_KCAL = 627.509474

def safe_name(name):
    return re.sub(r'[^\w\-.]', '_', str(name))

def parse_energy(text):
    matches = re.findall(r'TOTAL ENERGY\s+(' + FLOAT_RE + r')\s+Eh', text)
    if matches:
        val = matches[-1].replace("D", "E").replace("d", "e")
        return float(val)
    return None

def check_convergence(text):
    return bool(re.search(r'GEOMETRY OPTIMIZATION CONVERGED|normal termination of xtb', text, re.I))

def build_monomer_3d(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    res = AllChem.EmbedMolecule(mol, params)
    if res == -1:
        res = AllChem.EmbedMolecule(mol, useRandomCoords=True, randomSeed=42)
        if res == -1:
            return None
    try:
        AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
    except Exception:
        try:
            AllChem.UFFOptimizeMolecule(mol, maxIters=500)
        except Exception:
            pass
    return mol

def get_coords(mol):
    conf = mol.GetConformer()
    return conf.GetPositions()

def write_xyz(atom_symbols, coords, filepath):
    with open(filepath, 'w') as f:
        f.write(f"{len(atom_symbols)}\nGenerated by Pilot Interaction Pipeline\n")
        for sym, (x, y, z) in zip(atom_symbols, coords):
            f.write(f"{sym:<3} {x:12.6f} {y:12.6f} {z:12.6f}\n")

def run_xtb_opt(xyz_file, charge, work_dir):
    os.makedirs(work_dir, exist_ok=True)
    xyz_name = os.path.basename(xyz_file)
    dst_xyz = os.path.join(work_dir, xyz_name)
    if os.path.abspath(xyz_file) != os.path.abspath(dst_xyz):
        shutil.copyfile(xyz_file, dst_xyz)

    cmd = ['xtb', xyz_name, '--opt', 'normal', '-c', str(charge)]
    try:
        res = subprocess.run(
            cmd,
            cwd=work_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=180
        )
        out = res.stdout + "\n" + res.stderr
        converged = check_convergence(out)
        energy = parse_energy(out)
        
        opt_xyz = os.path.join(work_dir, 'xtbopt.xyz')
        final_xyz = opt_xyz if os.path.exists(opt_xyz) else dst_xyz
        return energy, converged, final_xyz, out
    except Exception as e:
        return None, False, None, str(e)

def compute_min_distance(xyz_file, n_ion_atoms):
    """Compute minimum distance between ion atoms and refrigerant atoms."""
    if not os.path.exists(xyz_file):
        return None
    with open(xyz_file, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]
    if len(lines) < 3:
        return None
    
    coords = []
    for line in lines[2:]:
        parts = line.split()
        if len(parts) >= 4:
            coords.append([float(parts[1]), float(parts[2]), float(parts[3])])
    
    coords = np.array(coords)
    if len(coords) <= n_ion_atoms:
        return None
    
    ion_coords = coords[:n_ion_atoms]
    ref_coords = coords[n_ion_atoms:]
    
    diff = ion_coords[:, np.newaxis, :] - ref_coords[np.newaxis, :, :]
    dists = np.sqrt(np.sum(diff**2, axis=-1))
    return float(np.min(dists))

def create_dimer_orientations(ion_mol, ref_mol, dist=3.2):
    """
    Generate 4 distinct spatial orientations to avoid local-minima traps.
    """
    ion_syms = [a.GetSymbol() for a in ion_mol.GetAtoms()]
    ref_syms = [a.GetSymbol() for a in ref_mol.GetAtoms()]
    combined_syms = ion_syms + ref_syms
    
    ion_xyz = get_coords(ion_mol)
    ref_xyz = get_coords(ref_mol)
    
    # Center both at origin
    ion_xyz = ion_xyz - np.mean(ion_xyz, axis=0)
    ref_xyz = ref_xyz - np.mean(ref_xyz, axis=0)
    
    orientations = []
    
    # Orient 1: +X axis
    c1 = ref_xyz + np.array([dist + np.max(ion_xyz[:,0]), 0, 0])
    orientations.append(np.vstack([ion_xyz, c1]))
    
    # Orient 2: -X axis
    c2 = ref_xyz + np.array([-dist + np.min(ion_xyz[:,0]), 0, 0])
    orientations.append(np.vstack([ion_xyz, c2]))
    
    # Orient 3: +Z axis
    c3 = ref_xyz + np.array([0, 0, dist + np.max(ion_xyz[:,2])])
    orientations.append(np.vstack([ion_xyz, c3]))
    
    # Orient 4: -Z axis with 90 deg Y-rotation
    R_y = np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]])
    ref_rot = np.dot(ref_xyz, R_y.T)
    c4 = ref_rot + np.array([0, 0, -dist + np.min(ion_xyz[:,2])])
    orientations.append(np.vstack([ion_xyz, c4]))
    
    return combined_syms, orientations, len(ion_syms)

def main():
    print("="*70)
    print("  Pilot GFN2-xTB Pairwise Interaction Energy Pipeline")
    print("="*70)
    
    # Check xTB availability
    try:
        chk = subprocess.run(['xtb', '--version'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        print(f"✅ xTB 引擎就绪: {chk.stdout.splitlines()[0] if chk.stdout else 'Active'}")
    except Exception:
        print("❌ 未在 PATH 中找到 xtb 可执行文件！请确认已安装并在终端可用。")
        return

    os.makedirs(WORK_DIR, exist_ok=True)
    
    # 1. Optimize Monomers First
    print("\n[Step 1/3] 优化单体孤立能量 (Monomer Reference Energies)...")
    monomer_energies = {}
    
    all_monomers = []
    for r_name, r_smi in PILOT_REFRIGERANTS.items():
        all_monomers.append(('Refrigerant', r_name, r_smi, 0))
    for a_name, a_smi in PILOT_ANIONS.items():
        all_monomers.append(('Anion', a_name, a_smi, -1))
    for c_name, c_smi in PILOT_CATIONS.items():
        all_monomers.append(('Cation', c_name, c_smi, 1))
        
    for cat, name, smi, charge in all_monomers:
        tag = safe_name(name)
        work = os.path.join(WORK_DIR, f"mono_{tag}")
        mol = build_monomer_3d(smi)
        xyz_file = os.path.join(work, f"{tag}.xyz")
        os.makedirs(work, exist_ok=True)
        write_xyz([a.GetSymbol() for a in mol.GetAtoms()], get_coords(mol), xyz_file)
        
        e, conv, _, _ = run_xtb_opt(xyz_file, charge, work)
        monomer_energies[name] = e
        print(f"  - {cat:<11} {name:<8}: E = {e:.6f} Eh (收敛: {conv})")

    # 2. Optimize Dimers across 4 Orientations
    print("\n[Step 2/3] 多构型采样计算配对复合物能量 (Multi-orientation Dimer Optimization)...")
    
    pair_tasks = []
    # Anion-Ref pairs (15)
    for a_name, a_smi in PILOT_ANIONS.items():
        for r_name, r_smi in PILOT_REFRIGERANTS.items():
            pair_tasks.append(('Anion-Ref', a_name, a_smi, -1, r_name, r_smi, 0, -1))
            
    # Cation-Ref pairs (6)
    for c_name, c_smi in PILOT_CATIONS.items():
        for r_name, r_smi in PILOT_REFRIGERANTS.items():
            pair_tasks.append(('Cation-Ref', c_name, c_smi, 1, r_name, r_smi, 0, 1))

    results = []
    for pair_type, ion_name, ion_smi, ion_q, ref_name, ref_smi, ref_q, dimer_q in pair_tasks:
        pair_tag = f"{safe_name(ion_name)}__{safe_name(ref_name)}"
        print(f"\n▶ 正在优化配对: [{pair_type}] {ion_name} + {ref_name} (Charge = {dimer_q})...")
        
        ion_mol = build_monomer_3d(ion_smi)
        ref_mol = build_monomer_3d(ref_smi)
        
        syms, orientations, n_ion_atoms = create_dimer_orientations(ion_mol, ref_mol)
        
        orient_results = []
        for o_idx, coords in enumerate(orientations, 1):
            sub_work = os.path.join(WORK_DIR, f"pair_{pair_tag}_ori{o_idx}")
            init_xyz = os.path.join(sub_work, "init.xyz")
            os.makedirs(sub_work, exist_ok=True)
            write_xyz(syms, coords, init_xyz)
            
            e_opt, conv, final_xyz, _ = run_xtb_opt(init_xyz, dimer_q, sub_work)
            d_min = compute_min_distance(final_xyz, n_ion_atoms) if final_xyz else None
            
            if e_opt is not None and conv:
                orient_results.append({
                    'orient_idx': o_idx,
                    'E_complex': e_opt,
                    'd_min': d_min
                })
                print(f"   Orientation {o_idx}: E = {e_opt:.6f} Eh | d_min = {d_min:.2f} Å (收敛 ✅)")
            else:
                print(f"   Orientation {o_idx}: 优化失败 / 未收敛 ❌")
        
        # Select minimum energy configuration
        if orient_results:
            best = min(orient_results, key=lambda x: x['E_complex'])
            e_complex = best['E_complex']
            best_d_min = best['d_min']
            e_ion = monomer_energies[ion_name]
            e_ref = monomer_energies[ref_name]
            
            delta_e_eh = e_complex - (e_ion + e_ref)
            delta_e_kcal = delta_e_eh * HARTREE_TO_KCAL
            
            print(f"   🏆 最优构型 (Ori {best['orient_idx']}): ΔE_int = {delta_e_kcal:.2f} kcal/mol | d_min = {best_d_min:.2f} Å")
            
            results.append({
                'Pair_Type': pair_type,
                'Ion_Name': ion_name,
                'Refrigerant': ref_name,
                'E_complex_Eh': e_complex,
                'E_ion_Eh': e_ion,
                'E_ref_Eh': e_ref,
                'Delta_E_int_kcal_mol': delta_e_kcal,
                'd_min_Angstrom': best_d_min,
                'Best_Orientation': best['orient_idx'],
                'N_Converged_Orientations': len(orient_results),
                'Status': 'Success'
            })
        else:
            print(f"   🚨 该配对全部构型优化失败！")
            results.append({
                'Pair_Type': pair_type,
                'Ion_Name': ion_name,
                'Refrigerant': ref_name,
                'E_complex_Eh': None,
                'E_ion_Eh': monomer_energies.get(ion_name),
                'E_ref_Eh': monomer_energies.get(ref_name),
                'Delta_E_int_kcal_mol': None,
                'd_min_Angstrom': None,
                'Best_Orientation': None,
                'N_Converged_Orientations': 0,
                'Status': 'Failed'
            })

    # 3. Export Summary
    df_out = pd.DataFrame(results)
    df_out.to_csv(OUTPUT_CSV, index=False)
    print("\n" + "="*70)
    print(f"✅ Pilot 配对相互作用能计算完成！结果已保存至: {OUTPUT_CSV}")
    print("="*70)

if __name__ == '__main__':
    main()
